spring:
  config:
    activate:
      on-profile:

  # 데이터 소스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/TEST?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 42gg
    password: pingPongpower42#

    jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
    logging:
      level:
        org.hibernate.SQL: debug


  security:
    oauth2.client:
      registration:
        42:
          client-id: "cd1431e55cd272b41ed09874172e04833b1918749ee6642acaef5b45f19c0b27"
          client-secret: "16f1c09b9b394017e87c4aeb55829647b6e0d69d6bba96f024b15cbdb723d529"

  # cors 설정
  cors:
    allowed-origins: 'http://localthos:3000'
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: '*'
    allowed-Credentials: false
    max-age: 3600

  info:
    web:
      frontUrl: 'http://localhost:3000'
