spring:
  profiles:
    active: local
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 42seoularcade@gmail.com
    password: ddejvefnkjscumxf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true