spring:
  config:
    activate:
      on-profile:

  # 데이터 소스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/MAIN?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 42gg
    password: pingPongpower42#

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false


  security:
    oauth2.client:
      registration:
        42:
          client-id: "353cdada0d271c99afd647ecb5c77f257750a212e40b613fe6847985bc1f21c6"
          client-secret: "88a2e5c53365399e884a05d6d09b7e251b187abc6f7b292a71fc1d2031dfdd9b"

  # Redis 설정
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379


logging:
  level:
    org.hibernate.SQL: debug

  # cors 설정
cors:
  allowed-origins: 'http://localhost:3000,http://localhost:8080,https://localhost:8080,https://localhost:3000,https://dev.api-42gg.shop,https://api.api-42gg.shop,https://api.42gg.shop,https://dev.api-42gg.shop,http://dev.api.42gg.shop'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  allowed-credentials: false
  max-age: 3600

info:
  web:
    frontUrl: 'http://localhost:3000'

