spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false



  config:
    activate:
      on-profile:
  # 데이터 소스 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/MARIADB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false


  security:
    oauth2.client:
      registration:
        42:
          client-id: "07036ff026b85153a047cf5188ce23a007d3e645b3293f71c4267f7c90917e04"
          client-secret: "b98634d8305b9d6a4750427bc3d6ecc403a7394916facb4947b4d9377b506bc7"

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: '*'
  allowed-Credentials: false
  max-age: 3600

info:
  web:
    frontUrl: 'http://localhost:8080'

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
